In [1]:
#1. Створіть одновимірний масив (вектор) з оберненими значеннями факторіалів натуральних чисел, починаючи з 2, та виведіть його значення.
import math

# Створити список чисел від 2 до 10 (включно)
number = list(range(2, 11))

# Обчислити факторіал для кожного числа
factorial = [math.factorial(n) for n in number]

# Обчислити обернене значення для кожного факторіала
inverse_factorial = [1/f for f in factorial]

# Вивести список обернених значень факторіалів
print(inverse_factorial)

[0.5, 0.16666666666666666, 0.041666666666666664, 0.008333333333333333, 0.001388888888888889, 0.0001984126984126984, 2.48015873015873e-05, 2.7557319223985893e-06, 2.755731922398589e-07]


In [2]:
#2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненимизначеннями синусів кожного натурального числа, починаючи з 1, та виведіть йогозначення.
import numpy as np

# Створити список чисел від 1 до 9 (включно) для заповнення матриці 3x3
numbers = list(range(1, 10))

# Обчислити синус для кожного числа та взяти обернене значення
inverse_sines = [1 / np.sin(n) for n in numbers]

# Перетворити список в матрицю 3x3
matrix = np.array(inverse_sines).reshape(3, 3)

# Вивести матрицю
print("Матриця обернених значень синусів:\n", matrix)


Матриця обернених значень синусів:
 [[ 1.18839511  1.09975017  7.0861674 ]
 [-1.32134871 -1.04283521 -3.57889955]
 [ 1.52210106  1.01075622  2.42648664]]


In [3]:
#Створіть масив розміром 4x4, заповніть його випадковими натуральними числами від 1 до 50 та знайдіть суму елементів кожного рядка.
import numpy as np

# Створити масив 4x4 з випадковими натуральними числами від 1 до 50
matrix = np.random.randint(1, 51, size=(4, 4))

matrix_sum = np.sum(matrix, axis=1)

print("Згенерована матриця:\n", matrix)
print("\nСуми елементів кожного рядка:", matrix_sum)

Згенерована матриця:
 [[25 27 33 30]
 [ 9 25 18 45]
 [ 9 14 14 21]
 [38 46 29  8]]

Суми елементів кожного рядка: [115  97  58 121]


In [4]:
#Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від -1.5 до 1.5 та виведіть його значення.
import numpy as np

# Створити матрицю 3x3 з випадковими дійсними числами від -1.5 до 1.5
matrix = np.random.uniform(-1.5, 1.5, size=(3, 3))

print("Згенерована матриця:\n", matrix)

Згенерована матриця:
 [[-0.62461065 -0.62445149  0.03652401]
 [ 1.20364006  0.22001195  0.32336435]
 [ 0.50389906 -0.49168487  0.48094923]]


In [5]:
#Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами в діапазоні
#від 8 до 12 та виконайте на них поелементні операції додавання, віднімання та множення.#
import numpy as np

# Створити два одновимірних масиви розміром 4 з випадковими цілими числами від 8 до 12
array1 = np.random.randint(8, 13, size=4)
array2 = np.random.randint(8, 13, size=4)

# Виконати поелементні операції
add_res = array1 + array2
sub_res = array1 - array2
multi_res = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("\nДодавання:", add_res)
print("Віднімання:", sub_res)
print("Множення:", multi_res)

Масив 1: [ 8  9 12 10]
Масив 2: [ 8 10 12 10]

Додавання: [16 19 24 20]
Віднімання: [ 0 -1  0  0]
Множення: [ 64  90 144 100]


In [6]:
#Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 15 та знайдіть їх добуток.
import numpy as np

# Створити дві матриці 4x4 з випадковими цілими числами від 1 до 15
matrix1 = np.random.randint(1, 16, size=(4, 4))
matrix2 = np.random.randint(1, 16, size=(4, 4))

product = np.dot(matrix1, matrix2)

print("Матриця 1:\n", matrix1)
print("\nМатриця 2:\n", matrix2)
print("\nДобуток матриць:\n", product)

Матриця 1:
 [[11 14  8  7]
 [10  9  7 14]
 [ 3  2 11  3]
 [ 8 11  3  8]]

Матриця 2:
 [[14  7 11 15]
 [ 5  3 10 11]
 [ 8  1  5  5]
 [ 8 14 15  7]]

Добуток матриць:
 [[344 225 406 408]
 [353 300 445 382]
 [164  80 153 143]
 [255 204 333 312]]


In [7]:
#Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та перемножте їх між собою.
import numpy as np

# Створити матрицю 4x2 з випадковими цілими числами від 1 до 3
matrix1 = np.random.randint(1, 4, size=(4, 2))

# Створити матрицю 2x2 з випадковими цілими числами від 1 до 3
matrix2 = np.random.randint(1, 4, size=(2, 2))

# Перемножити матриці
result = np.dot(matrix1, matrix2)

print("Матриця 1:\n", matrix1)
print("\nМатриця 2:\n", matrix2)
print("\nРезультат перемноження матриць:\n", result)

Матриця 1:
 [[1 3]
 [2 3]
 [3 2]
 [3 3]]

Матриця 2:
 [[3 2]
 [1 1]]

Результат перемноження матриць:
 [[ 6  5]
 [ 9  7]
 [11  8]
 [12  9]]


In [8]:
#Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
import numpy as np

# Створити матрицю 2x2 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(2, 2))

# Знайти обернену матрицю
inverse_matrix = np.linalg.inv(matrix)

print("Оригінальна матриця:\n", matrix)
print("\nОбернена матриця:\n", inverse_matrix)

Оригінальна матриця:
 [[ 3 10]
 [ 2  7]]

Обернена матриця:
 [[  7. -10.]
 [ -2.   3.]]


In [9]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -4 до 10 та транспонуйте її.
import numpy as np

# Створити матрицю 3x3 з випадковими дійсними числами від -4 до 10
matrix = np.random.uniform(-4, 10, size=(3, 3))

# Транспонувати матрицю
transposed_matrix = np.transpose(matrix)

print("Оригінальна матриця:\n", matrix)
print("\nТранспонована матриця:\n", transposed_matrix)

Оригінальна матриця:
 [[ 9.07962964 -2.43314726  8.07568412]
 [ 6.7843941  -1.91525798  5.00707329]
 [-3.46651441  3.24464651  5.69098857]]

Транспонована матриця:
 [[ 9.07962964  6.7843941  -3.46651441]
 [-2.43314726 -1.91525798  3.24464651]
 [ 8.07568412  5.00707329  5.69098857]]


In [10]:
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими
# дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

# Створити матрицю 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)

# Створити вектор 4x1 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(4, 1)

# Знайти добуток матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("\nВектор:\n", vector)
print("\nРезультат множення матриці на вектор:\n", result)

Матриця:
 [[0.99199005 0.09087325 0.56969275 0.68906011]
 [0.0791902  0.35036602 0.91850466 0.74202783]
 [0.80610023 0.52519925 0.03147123 0.77781198]]

Вектор:
 [[0.12679826]
 [0.6814818 ]
 [0.28528987]
 [0.3696725 ]]

Результат множення матриці на вектор:
 [[0.60496522]
 [0.7851566 ]
 [0.75663996]]


In [11]:
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими
# цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

# Створення матриці 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створення вектора 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Знаходження добутку матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:\n", matrix)
print("\nВектор:\n", vector)
print("\nРезультат множення матриці на вектор:\n", result)

Матриця:
 [[0.02487648 0.71563556 0.28378353]
 [0.68320493 0.10448478 0.32559309]]

Вектор:
 [[9]
 [9]
 [9]]

Результат множення матриці на вектор:
 [[ 9.21866016]
 [10.01954523]]


In [12]:
#Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть відношення всіх
#елементів першої матриці до відповідних елементів другої матриці (поелементне ділення).
import numpy as np

# Створити дві матриці 3x3 з випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

# Знайти відношення всіх елементів першої матриці до відповідних елементів другої матриці
result = matrix1 / matrix2

print("Матриця 1:\n", matrix1)
print("\nМатриця 2:\n", matrix2)
print("\nРезультат поелементного ділення:\n", result)

Матриця 1:
 [[3 4 5]
 [1 2 3]
 [2 2 3]]

Матриця 2:
 [[4 3 1]
 [2 1 4]
 [1 5 2]]

Результат поелементного ділення:
 [[0.75       1.33333333 5.        ]
 [0.5        2.         0.75      ]
 [2.         0.4        1.5       ]]


In [13]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть різницю їх елементів.
import numpy as np

# Створити дві матриці 4x4 з випадковими дійсними числами від 0 до 1
matrix1 = np.random.rand(4, 4)
matrix2 = np.random.rand(4, 4)

# Знайти різницю елементів матриць
difference = matrix1 - matrix2

print("Матриця 1:\n", matrix1)
print("\nМатриця 2:\n", matrix2)
print("\nРізниця матриць:\n", difference)

Матриця 1:
 [[0.53409263 0.70162366 0.83766548 0.63219678]
 [0.12859443 0.76855613 0.60606192 0.1382617 ]
 [0.58309469 0.63873148 0.45917173 0.61187651]
 [0.08672157 0.30139499 0.40112299 0.15721701]]

Матриця 2:
 [[0.37526912 0.33606151 0.75661714 0.98091624]
 [0.36656044 0.21093527 0.82091278 0.41146518]
 [0.99745351 0.64475274 0.88471142 0.938747  ]
 [0.79268061 0.64813724 0.59951087 0.04098857]]

Різниця матриць:
 [[ 0.15882351  0.36556216  0.08104834 -0.34871946]
 [-0.23796601  0.55762086 -0.21485086 -0.27320348]
 [-0.41435883 -0.00602126 -0.4255397  -0.32687049]
 [-0.70595904 -0.34674225 -0.19838788  0.11622843]]


In [14]:
#Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть суму елементів на побічній діагоналі.
import numpy as np

# Створити матрицю 4x4 з випадковими дійсними числами від -10 до 10
matrix = np.random.uniform(-10, 10, size=(4, 4))

# Знайти суму елементів на побічній діагоналі
secondary_diagonal_sum = np.trace(np.fliplr(matrix))

print("Згенерована матриця:\n", matrix)
print("\nСума елементів на побічній діагоналі:", secondary_diagonal_sum)

Згенерована матриця:
 [[-9.27081405 -5.02891886 -0.2192085   7.16995609]
 [-8.87604452 -3.10800236 -9.20219469  7.16053263]
 [-6.37516897 -9.72709267 -0.48283134 -4.3438826 ]
 [-1.97811959  1.55715768  8.5311423   8.16680476]]

Сума елементів на побічній діагоналі: -13.737450861549302


In [15]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть
#вектор-стовпчик, що містить суму квадратів елементів кожного стовпця матриці
import numpy as np

# Створити матрицю 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

# Обчислити суму квадратів елементів кожного стовпця
column_sums_of_squares = np.sum(matrix ** 2, axis=0)

# Перетворити результат на вектор-стовпчик
column_sums_of_squares = column_sums_of_squares.reshape(-1, 1)

print("Матриця:\n", matrix)
print("\nВектор-стовпчик суми квадратів елементів кожного стовпця:\n", column_sums_of_squares)

Матриця:
 [[0.63462005 0.25781773 0.87535505]
 [0.69068655 0.52061579 0.74699565]
 [0.61301575 0.06727228 0.59823644]]

Вектор-стовпчик суми квадратів елементів кожного стовпця:
 [[1.25557883]
 [0.34203634]
 [1.68213579]]


In [16]:
#Ми створювали матриці та вектори, заповнювали їх випадковими числами, а потім виконували такі дії, як множення, додавання, віднімання і так далі.
#Ми також обчислювали суми елементів, добутки та середні значення.